cmsDriver.py Configuration/GenProduction/python/EWKZ2Jets_ZToQQ_GEN_fragment.py \
    --python_filename EWKZ2Jets_ZToQQ_GENSIM_cfg.py \
    --eventcontent RAWSIM \
    --customise Configuration/DataProcessing/Utils.addMonitoring \
    --datatier GEN-SIM \
    --fileout file:EWKZ2Jets_ZToQQ_GENSIM.root \
    --conditions 124X_mcRun3_2022_realistic_postEE_v1 \
    --beamspot Realistic25ns13p6TeVEarly2022Collision \
    --step LHE,GEN,SIM \
    --geometry DB:Extended \
    --era Run3 \
    --mc \
    --no_exec \
    -n 100
